src/main/java/de/samply/bbmri/negotiator/control/ApplicationBean.java
/**
 * Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
 * Deutsches Krebsforschungszentrum in Heidelberg
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.bbmri.negotiator.control;

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.util.Map;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;

import de.samply.bbmri.negotiator.db.util.DbUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.docuverse.identicon.IdenticonUtil;

import de.samply.bbmri.negotiator.*;
import de.samply.bbmri.negotiator.jooq.Tables;
import de.samply.bbmri.negotiator.jooq.tables.records.PersonRecord;

/**
 * The Class ApplicationBean.
 */
@ManagedBean(eager =  true)
@ApplicationScoped
public class ApplicationBean implements Serializable {
    
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    private final static Logger logger = LoggerFactory.getLogger(ApplicationBean.class);

    /**
     * Gets the faces context.
     *
     * @return the faces context
     */
    private ServletContext getFacesContext() {
        return (ServletContext)
                FacesContext.getCurrentInstance().getExternalContext().getContext();
    }

    /**
     * Initializes the database version tables and checks for necessary upgrades.
     */
    @PostConstruct
    public void initializeDbUpgrades() {
        try (Config config = ConfigFactory.get()) {
            /**
             * In case the application has been started in development mode, deploy the dummy data.
             */
            if(NegotiatorConfig.get().getNegotiator().deployDummyData()) {
                logger.info("Developer wants, that I deploy dummy data");

                if(!NegotiatorConfig.getNewDatabaseInstallation()) {
                    logger.debug("Not a new DB installation. Bailing on deploying Dummy Data");
                    return;
                }

                DbUtil.executeSQLFile(config.get(), getClass().getClassLoader(), "/sql/dummyData.sql");

                Random random = new Random();

                /**
                 * Generate identicons for every user in the dummy data and store them in the DB.
                 */
                for(PersonRecord person : config.dsl().selectFrom(Tables.PERSON)) {
                    if(person.getPersonImage() == null) {
                        logger.info("Generating identicon for user {}", person.getAuthName());
                        person.setPersonImage(IdenticonUtil.generateIdenticon(new BigInteger(64, random).intValue(), 256));
                        person.update();
                    }
                }

                config.get().commit();
            }

        } catch (Exception e) {
            e.printStackTrace();
            NegotiatorConfig.get().setMaintenanceMode(true);
        }
    }

    /**
     * Gets the version.
     *
     * @return the version
     */
    public String getVersion() {
        return ServletUtil.getVersion(getFacesContext());
    }

    /**
     * Redirect to index page.
     */
    public void redirectToIndexPage() {
        FacesContext fc = FacesContext.getCurrentInstance();
        ConfigurableNavigationHandler nav = (ConfigurableNavigationHandler) fc.getApplication().getNavigationHandler();
        nav.performNavigation("index");
    }

    public Map<NegotiatorStatus.NegotiatorTaskType, NegotiatorStatus.NegotiatorTaskStatus> getSuccessStatus() {
        return NegotiatorStatus.get().getSuccessMap();
    }

    public Map<NegotiatorStatus.NegotiatorTaskType, NegotiatorStatus.NegotiatorTaskStatus> getFailStatus() {
        return NegotiatorStatus.get().getFailMap();
    }

    /**
     * Returns the JSF version of the currently used JSF library
     * @return
     */
    public String getJSFVersion() {
        return FacesContext.class.getPackage().getImplementationVersion();
    }

    /**
     * Returns the JSF vendor of the currently used JSF library
     * @return
     */
    public String getJSFTitle() {
        return FacesContext.class.getPackage().getImplementationTitle();
    }

    /**
     * Returns the database version.
     *
     * @return the database version
     */
    public String getDBVersion() {
        return "" + Constants.DB_REQUIRED_VERSION;
    }

    /**
     * Returns the branch of the commit
     * @return
     */
    public String getGitBranch() {
        return ServletUtil.getBuildCommitBranch(getFacesContext());
    }

    /**
     * Returns the Git Commit SHA ID.
     * @return
     */
    public String getGitCommitId() {
        return ServletUtil.getBuildCommitId(getFacesContext());
    }
}

src/main/webapp/admin/debug.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="default.xhtml">

    <ui:param name="bodyClass" value="container"/>

    <ui:define name="body">

        <h3>#{label['admin.debug.query']}</h3>

        <h:form styleClass="form-horizontal">
            <h:commandButton action="#{adminDebugBean.loadQueries()}" value="#{label['admin.debug.click']}"
                             styleClass="btn btn-default"/>
        </h:form>

        <h:dataTable rendered="#{adminDebugBean.queries.size() > 0}" value="#{adminDebugBean.queries}" var="query"
                     columnClasses="columns,columns,columns,columns,columns,columns,columns,columns,columns,columns,columns"
                     rowClasses="rows" class="table-striped table-bordered table-responsive table-fullwidth">

            <h:column>
                <f:facet name="header">Id</f:facet>
                #{query.getId()}
            </h:column>
            <h:column>
                <f:facet name="header">Title</f:facet>
                <h:panelGroup style=" overflow: hidden; text-overflow: ellipsis; display:block; white-space: nowrap">
                    #{query.getTitle()}
                </h:panelGroup>
            </h:column>
            <h:column>
                <f:facet name="header">Text</f:facet>
                <h:panelGroup style=" overflow: hidden; text-overflow: ellipsis; display:block; white-space: nowrap">
                    #{query.getText()}
                </h:panelGroup>
            </h:column>
            <h:column>
                <f:facet name="header">QueryCreationTime</f:facet>
                #{query.getQueryCreationTime()}
            </h:column>
            <h:column>
                <f:facet name="header">ResearcherId</f:facet>
                #{adminDebugBean.getUserName(query.getResearcherId())}
            </h:column>
            <h:column>
                <f:facet name="header">JsonText</f:facet>
                <h:panelGroup style=" overflow: hidden; text-overflow: ellipsis; display:block; white-space: nowrap">
                    #{query.getJsonText()}
                </h:panelGroup>
            </h:column>
            <h:column>
                <f:facet name="header">Attachments</f:facet>
                #{query.getNumAttachments()}
            </h:column>
            <h:column>
                <f:facet name="header">NegotiatorToken</f:facet>
                <h:panelGroup style=" overflow: hidden; text-overflow: ellipsis; display:block; white-space: nowrap">
                    #{query.getNegotiatorToken()}
                </h:panelGroup>
            </h:column>
            <h:column>
                <f:facet name="header">ValidQuery</f:facet>
                #{query.getValidQuery()}
            </h:column>
            <h:column>
                <f:facet name="header">RequestDescription</f:facet>
                #{query.getRequestDescription()}
            </h:column>
            <h:column>
                <f:facet name="header">EthicsVote</f:facet>
                #{query.getEthicsVote()}
            </h:column>
            <h:column>
                <f:facet name="header">Negotiation Started Time</f:facet>
                #{query.getNegotiationStartedTime().toString()}
            </h:column>
            <!--
            <h:column>
                <f:facet name="header">Biobanks and Collections</f:facet>
                <h:panelGroup id="queryCollectionsDisplay" layout="block">

                    <h:panelGroup styleClass="text" layout="block">
                        <h:outputLabel value="#{label['queryview.title.amountMatchingCollections']}"/>
                        <h:outputText
                                value="#{adminDebugBean.getMatchingBiobanks(query.getId())} #{adminDebugBean.getReachableCollections(query.getId())}"
                                style="margin-left: 22px;">
                        </h:outputText>

                        <a href="#" data-toggle="collapse" data-target="#collection-list" class="label label-default">
                            #{label['queryview.action.showcollections']}
                        </a>
                    </h:panelGroup>

                    <div id="collection-list-{query.getId()}" class="collapse">
                        #{adminDebugBean.getJsTreeJson(query.getId())}
                    </div>
                    <h:outputScript>
                        $(function() {
                            var data1= JSON.parse(document.getElementById("collection-list-{query.getId()}").innerHTML);
                            $('#collection-list-{query.getId()}').jstree({
                                'core': {
                                    'data': data1
                                }
                            });
                        });
                    </h:outputScript>
                </h:panelGroup>
            </h:column>
            -->

            <h:column>
                <f:facet name="header">Reset Negotiation</f:facet>
                <h:form id="form">
                    <!-- Show the start negotiation button only if the negotiation hasn't started yet for a given query. -->
                    <h:commandButton id="resetNegotiation"
                                     rendered="#{query.getNegotiationStartedTime() != null}"
                                     value="#{label['querydetail.action.resetNegotiation.buttonText']}"
                                     action="#{adminDebugBean.restNegotiation(query.getId())}"
                                     title="#{label['querydetail.tooltip.restNegotiation']}"
                                     styleClass="btn btn-primary" style="margin-top: 40px"/>
                </h:form>
            </h:column>
        </h:dataTable>

    </ui:define>
</ui:composition>

src/main/webapp/admin/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
>

<h:head>
    <title><ui:insert name="title">BBMRI.negotiator</ui:insert></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    
    <ui:include src="../components/styles.xhtml" />

    <ui:insert name="head" />
</h:head>

<h:body styleClass="#{bodyClass}">

    <ui:include src="navbar.xhtml" />

    <div class="navbar-shadow" />

    <ui:insert name="body" />

</h:body>
</html>

src/main/webapp/admin/directories.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                template="default.xhtml">

    <ui:param name="bodyClass" value="container"/>

    <ui:define name="body">

        <h3>#{label['admin.directories']}</h3>
        Build: #{label['build.date']}

        <table class="table table-hover">
            <thead>
            <tr>
                <th>#{label['directory.table.id']}</th>
                <th>#{label['directory.table.name']}</th>
                <th>#{label['directory.table.url']}</th>
                <th>#{label['directory.table.description']}</th>
                <th>#{label['directory.table.resourceBiobanks']}</th>
                <th>#{label['directory.table.resourceCollections']}</th>
                <th>#{label['directory.table.directorySyncActive']}</th>
                <th>#{label['directory.table.actions']}</th>
            </tr>
            </thead>
            <tbody>
            <ui:repeat value="#{directoryBean.directories}" var="directory">
                <tr class="#{directory.syncActive ? 'success' : 'danger'}">
                    <td>#{directory.id}</td>
                    <td>#{directory.name}</td>
                    <td>#{directory.url}</td>
                    <td>#{directory.description}</td>
                    <td>#{directory.resourceBiobanks}</td>
                    <td>#{directory.resourceCollections}</td>
                    <td>#{directory.syncActive}</td>
                    <td>
                        <h:form>
                            <h:button value="#{label['directory.table.actions.syncDirectory']}"
                                      title="#{label['directory.table.actions.syncDirectory.toottip']}"
                                      action="#{directoryBean.syncDirectory(directory.id, directory.name, directory.restUrl, directory.resourceBiobanks, directory.resourceCollections, directory.apiUsername, directory.apiPassword)}" />
                        </h:form>
                        <h:button outcome="newDirectory"
                                  value="#{label['directory.table.actions.editDirectory']}"
                                  title="#{label['directory.table.actions.editDirectory.toottip']}"
                                  styleClass="btn btn-primary" style="margin-top: 10px">

                            <f:param name="listOfDirectoryId" value="#{directory.id}"/>
                        </h:button>
                    </td>
                </tr>
            </ui:repeat>
            </tbody>
        </table>

        <h:button outcome="newDirectory"
                  value="#{label['directory.table.actions.addDirectory']}"
                  title="#{label['directory.table.actions.addDirectory']}"
                  styleClass="btn btn-primary" style="margin-top: 10px;margin-bottom: 10px;">
        </h:button>

        <div>
            Git-Branch: #{applicationBean.gitBranch}, Git-Commit-ID: #{applicationBean.gitCommitId}, Version: #{applicationBean.version}
        </div>

    </ui:define>

</ui:composition>

src/main/webapp/admin/email.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="default.xhtml">

	<ui:param name="bodyClass" value="container"/>

	<ui:define name="body">

		<h3>#{label['admin.email']}</h3>

		<h:messages showSummary="true" showDetail="true"
					styleClass="list-group"
					errorClass="list-group-item list-group-item-danger"
					fatalClass="list-group-item list-group-item-danger"
					infoClass="list-group-item list-group-item-info" />

		<h:form styleClass="form-horizontal">
			<div class="col-md-12">
				<div class="form-group">
					<h:outputLabel for="emailAddress" value="#{label['admin.email.address']}" styleClass="col-sm-2 control-label"/>
					<div class="col-sm-10">
						<h:inputText value="#{adminEmailBean.emailAddress}" id="emailAddress" styleClass="form-control"/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<h:commandButton action="#{adminEmailBean.sendEmail}" value="#{label['admin.email.send']}" styleClass="btn btn-default"/>
					</div>
				</div>
			</div>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/admin/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="default.xhtml">

	<ui:param name="bodyClass" value="container"/>

	<ui:define name="body">

		<h3>#{label['admin.status']}</h3>
        Build: #{label['build.date']}

		<table class="table table-hover">
			<thead>
				<tr>
					<th>#{label['admin.table.taskType']}</th>
					<th>#{label['admin.table.lastSuccess']}</th>
					<th>#{label['admin.table.lastSuccessMessage']}</th>
					<th>#{label['admin.table.lastFail']}</th>
					<th>#{label['admin.table.lastFailMessage']}</th>
				</tr>
			</thead>
			<tbody>
				<ui:repeat value="#{applicationBean.successStatus.keySet().toArray()}" var="type">
					<tr class="#{applicationBean.successStatus.get(type).date.after(applicationBean.failStatus.get(type).date) ? 'success' : 'danger'}">
						<td>#{label[type]}</td>
						<td>#{applicationBean.successStatus.get(type).date}</td>
						<td>#{applicationBean.successStatus.get(type).message}</td>
						<td>#{applicationBean.failStatus.get(type).date}</td>
						<td>#{applicationBean.failStatus.get(type).message}</td>
					</tr>
				</ui:repeat>
			</tbody>
		</table>

		<div>
			Git-Branch: #{applicationBean.gitBranch}, Git-Commit-ID: #{applicationBean.gitCommitId}, Version: #{applicationBean.version}
		</div>

	</ui:define>

</ui:composition>

src/main/webapp/admin/navbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<h:panelGroup styleClass="container" layout="block" id="navbar">
			<h:panelGroup layout="block" styleClass="navbar-header">

				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<h:link outcome="/index" styleClass="navbar-brand">
					<span class="projectName">#{label['queryview.bbmri']}<span class="bbmriModule">#{label['admin.negotiator']}</span></span>
				</h:link>
			</h:panelGroup>

			<h:panelGroup layout="block" styleClass="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<h:link outcome="index">
							#{label['admin.status']}
						</h:link>
					</li>
					<li>
						<h:link outcome="directories">
							#{label['admin.directories']}
						</h:link>
					</li>
					<li>
						<h:link outcome="sudo">
							#{label['admin.sudo']}
						</h:link>
					</li>
					<li>
						<h:link outcome="email">
							#{label['admin.email']}
						</h:link>
					</li>
					<li>
						<h:link outcome="debug">
							#{label['admin.debug']}
						</h:link>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right navbar-user">
					<li class="pull-right">
						<h:link outcome="/index">
							<i class="fa fa-sign-out userIcon"/>
						</h:link>
					</li>
					<li class="pull-right">
						<h:link outcome="/admin/index">Version #{applicationBean.version}, DB #{applicationBean.DBVersion},
							#{applicationBean.JSFTitle} #{applicationBean.JSFVersion}</h:link>
					</li>
				</ul>
			</h:panelGroup>
		</h:panelGroup>

	</nav>
</ui:composition>

src/main/webapp/admin/sudo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="default.xhtml">

	<f:metadata>
		<f:viewAction action="#{adminBean.initialize}" />
	</f:metadata>

	<ui:param name="bodyClass" value="container"/>

	<ui:define name="body">

		<h3>#{label['admin.sudo']}</h3>
		<h:form>
			<h:outputText value="Select user to sudo." />

			<table class="table table-hover">
				<thead>
				<tr>
					<th>#{label['admin.sudo.user.name']}</th>
					<th>#{label['admin.sudo.take.Identitiy']}</th>
				</tr>
				</thead>

				<tbody>
				<ui:repeat value="#{adminBean.allUsers}" var="alle">
				     <tr>
							<td>#{alle.getAuthName()}</td>
							<td><h:commandButton value="Switch user" action="#{adminBean.switchUser(alle.getAuthSubject())}" /></td>
					</tr>
				</ui:repeat>

				</tbody>

			</table>



		</h:form>

	</ui:define>

</ui:composition>