src/main/java/de/samply/bbmri/negotiator/control/owner/OwnerQueriesBean.java
/**

 * Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
 * Deutsches Krebsforschungszentrum in Heidelberg
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.bbmri.negotiator.control.owner;

import java.io.Serializable;
import java.sql.SQLException;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import de.samply.bbmri.negotiator.Config;
import de.samply.bbmri.negotiator.ConfigFactory;
import de.samply.bbmri.negotiator.control.SessionBean;
import de.samply.bbmri.negotiator.control.UserBean;
import de.samply.bbmri.negotiator.db.util.DbUtil;
import de.samply.bbmri.negotiator.jooq.enums.Flag;
import de.samply.bbmri.negotiator.model.OwnerQueryStatsDTO;

/**
 * Manages the query view for owners
 */
@ManagedBean
@ViewScoped
public class OwnerQueriesBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private List<OwnerQueryStatsDTO> queries;

	/**
	 * The currently active flag filter. Set this to whatever flag you want and you will see the flagged queries only.
	 */
	private Flag flagFilter = Flag.UNFLAGGED;

	@ManagedProperty(value = "#{userBean}")
	private UserBean userBean;

	@ManagedProperty(value = "#{sessionBean}")
    private SessionBean sessionBean;


	/**
	 * Initializes this bean by loading all queries for the current researcher.
	 */
	@PostConstruct
	public void init() {

	}

	/**
	 * Leave query as a bio bank owner.
	 *
	 * @param queryDto
	 * @return
	 */
	public void ignoreQuery(OwnerQueryStatsDTO queryDto) {
		try (Config config = ConfigFactory.get()) {
			config.get().commit();
			queries = null;
			flagQuery(queryDto, Flag.IGNORED);
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Mark query as starred
	 * @param queryDto
	 */
	public void starQuery(OwnerQueryStatsDTO queryDto){
		flagQuery(queryDto, Flag.STARRED);
	}

	/**
	 * Mark query as archived
	 * @param queryDto
	 */
	public void archiveQuery(OwnerQueryStatsDTO queryDto){
		flagQuery(queryDto, Flag.ARCHIVED);
	}

	/**
	 * Mark the given query with the given flag.
	 *
	 * If Postgresql supported SQL standard Merge statement, the query look like this :
	 * 		 config.dsl().insertInto(Tables.FLAGGED_QUERY, Tables.FLAGGED_QUERY.QUERY_ID, Tables.FLAGGED_QUERY.PERSON_ID, Tables.FLAGGED_QUERY.FLAG).
	 *		 values(queryId, userBean.getUserId(), flag)
	 *		.onDuplicateKeyUpdate()
	 *		.set(Tables.FLAGGED_QUERY.QUERY_ID,queryId)
	 *		.set(Tables.FLAGGED_QUERY.PERSON_ID,userBean.getUserId())
	 *		.set(Tables.FLAGGED_QUERY.FLAG, flag).execute();
	 *
	 * But with the current jooq version this does not work, since there is no way to set the postgresql version to 9.5 (necessary for this to work).
	 *
	 * @param queryDto
	 * @param flag
	 */
	private void flagQuery(OwnerQueryStatsDTO queryDto, Flag flag) {
		try (Config config = ConfigFactory.get()) {
			DbUtil.flagQuery(config, queryDto, flag, userBean.getUserId());
			config.get().commit();
			queries = null;
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Sorts the queries such that the archived ones appear at the end.
	 *
	 * @return
	 */
	public void sortQueries(){
		if (queries == null || queries.isEmpty()) {
			return;
		} else {
		    Collections.sort(queries, new Comparator<OwnerQueryStatsDTO>() {
                @Override
                public int compare(OwnerQueryStatsDTO obj1, OwnerQueryStatsDTO obj2) {
                    if(obj1.isArchived() && obj2.isArchived()) {
                        return 0;
                    } else if(obj1.isArchived()) {
                        return 1;
                    } else if(obj2.isArchived()) {
                        return -1;
                    } else {
                        return 0;
                    }
                }
            });

	    }
	}

	/**
	 * Returns the list of queries in which the current biobank owner is a part of,
	 * filters by search terms if any are provided
	 *
	 * @return
	 */
	public List<OwnerQueryStatsDTO> getQueries() {
		if (queries == null) {
			try (Config config = ConfigFactory.get()) {

			    queries = DbUtil.getOwnerQueries(config, userBean.getUserId(), getFilterTerms(),
					        flagFilter);
				sortQueries();

			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		return queries;
	}

	/**
	 * Add search filter
	 */
	public void addFilter() {
		queries = null;
		sessionBean.addFilter();
	}

	/**
	 * Removes the search filter.
	 *
	 * @param arg
	 *
	 */
	public void removeFilter(String arg) {
		queries = null;
		sessionBean.removeFilter(arg);
	}

	/**
	 * Split search terms by list of delimiters
	 * @return unique search terms
	 */
	public Set<String> getFilterTerms() {
		Set<String> filterTerms = new HashSet<String>();
		for(String filters : sessionBean.getFilters()) {
			// split by 0 or more spaces, followed by either 'and','or', comma or more spaces
			String[] filterTermsArray = filters.split("\\s*(and|or|,)\\s*");
			Collections.addAll(filterTerms, filterTermsArray);
		}
		return filterTerms;
	}


	public SessionBean getSessionBean() {
		return sessionBean;
	}

	public void setSessionBean(SessionBean sessionBean) {
		this.sessionBean = sessionBean;
	}

	public void setQueries(List<OwnerQueryStatsDTO> queries) {
		this.queries = queries;
	}

	public UserBean getUserBean() {
		return userBean;
	}

	public void setUserBean(UserBean userBean) {
		this.userBean = userBean;
	}

	public Flag getFlagFilter() {
		return flagFilter;
	}

	public void setFlagFilter(Flag flagFilter) {
		this.flagFilter = flagFilter;
	}

	public String getPagetitle() {
		return "pagetitle_"+flagFilter;
	}
}

src/main/java/de/samply/bbmri/negotiator/control/owner/OwnerQueriesDetailBean.java
/**
 * Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
 * Deutsches Krebsforschungszentrum in Heidelberg
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.bbmri.negotiator.control.owner;

import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.*;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import com.fasterxml.jackson.databind.ObjectMapper;
import de.samply.bbmri.negotiator.Config;
import de.samply.bbmri.negotiator.ConfigFactory;
import de.samply.bbmri.negotiator.NegotiatorConfig;
import de.samply.bbmri.negotiator.config.Negotiator;
import de.samply.bbmri.negotiator.control.SessionBean;
import de.samply.bbmri.negotiator.control.UserBean;
import de.samply.bbmri.negotiator.db.util.DbUtil;
import de.samply.bbmri.negotiator.jooq.enums.Flag;
import de.samply.bbmri.negotiator.jooq.tables.pojos.Person;
import de.samply.bbmri.negotiator.jooq.tables.pojos.Query;
import de.samply.bbmri.negotiator.jooq.tables.records.BiobankRecord;
import de.samply.bbmri.negotiator.model.CommentPersonDTO;
import de.samply.bbmri.negotiator.model.OfferPersonDTO;
import de.samply.bbmri.negotiator.model.OwnerQueryStatsDTO;
import de.samply.bbmri.negotiator.model.QueryAttachmentDTO;
import de.samply.bbmri.negotiator.rest.RestApplication;
import de.samply.bbmri.negotiator.rest.dto.QueryDTO;
import org.apache.commons.codec.digest.DigestUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Manages the query detail view for owners
 */
@ManagedBean
@ViewScoped
public class OwnerQueriesDetailBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Logger logger = LoggerFactory.getLogger(OwnerQueriesDetailBean.class);

	@ManagedProperty(value = "#{userBean}")
	private UserBean userBean;

	@ManagedProperty(value = "#{sessionBean}")
    private SessionBean sessionBean;

	/**
	 * The structured query object
	 */
	private String humanReadableQuery = null;

	/**
     * The OwnerQueryStatsDTO object used to get all the information for queries.
     */
	private List<OwnerQueryStatsDTO> queries;

	/**
	 * The currently active flag filter. Set this to whatever flag you want and you will see the flagged queries only.
	 */
	private Flag flagFilter = Flag.UNFLAGGED;

	/**
     * The id of the query selected from owner.index.xhtml page, if there is one
     */
	private int queryId;

	/**
     * The selected query, if there is one
     */
	private Query selectedQuery = null;

	 /**
     * The input text box for the user to make a comment.
     */
    private String commentText;

	/**
     * The list of comments for the selected query
     */
    private List<CommentPersonDTO> comments;

    /**
     * The list of biobanks this owner is associated with
     */
    private List<BiobankRecord> associatedBiobanks;

    /**
     * The list of attachments associated with a certain query.
     */
    private List<QueryAttachmentDTO> attachments;

	/**
	 * Map of saved filename and realname of attachments
	 */
	private HashMap<String, String> attachmentMap = null;

	/**
     * The list of offers(private comments) for the selected query
     */
    private List<OfferPersonDTO> offerPersonDTO;

	/**
	 * A boolean that specifies if a non-confidential view must be rendered for a non-confidential biobanker(for connector) and vise versa
	 */
	private boolean nonConfidential = true;

	/**
	 * The list of offerPersonDTO's, hence it's a list of lists.
	 */
	private List<List<OfferPersonDTO>> listOfSampleOffers = new ArrayList<>();
    /**
     * initialises the page by getting all the comments for a selected(clicked on) query
     */
	public String initialize() {
        setNonConfidential(false);

        try(Config config = ConfigFactory.get()) {
            setComments(DbUtil.getComments(config, queryId));

			associatedBiobanks = DbUtil.getAssociatedBiobanks(config, queryId, userBean.getUserId());

			for (int i = 0; i < associatedBiobanks.size(); ++i) {
				listOfSampleOffers.add(DbUtil.getOffers(config, queryId, associatedBiobanks.get(i).getId()));
			}

            /**
             * Get all the attachments for selected query.
             */
            setAttachments(DbUtil.getQueryAttachmentRecords(config, queryId));

            /**
             * Get the selected(clicked on) query from the list of queries for the owner
             */
            for(OwnerQueryStatsDTO ownerQueryStatsDTO : getQueries()) {
            	if(ownerQueryStatsDTO.getQuery().getId() == queryId) {
            		selectedQuery = ownerQueryStatsDTO.getQuery();
            	}
            }

            if(selectedQuery != null) {
				RestApplication.NonNullObjectMapper mapperProvider = new RestApplication.NonNullObjectMapper();
				ObjectMapper mapper = mapperProvider.getContext(ObjectMapper.class);
				QueryDTO queryDTO = mapper.readValue(selectedQuery.getJsonText(), QueryDTO.class);
				//TODO: Human readable need rework
				//setHumanReadableQuery(queryDTO.getHumanReadable());
				setHumanReadableQuery(queryDTO.getHumanReadable());
				//setHumanReadableQuery("TODO");
			} else {

            	/*
            	 * Check why the selected query is null. There could be two possibilities.
            	 */
                Query query = DbUtil.checkIfQueryExists(config, queryId);
            	if(query == null){

					/**
					 * If 'query' is null, it means that the 'selected query' simply does not exist in our system.
					 */
					return "/errors/not-found.xhtml";

				}else{

            		/*
            		 *If 'query' is not null this means the biobanker does not have access privileges to the 'selected query'.
            		 * We give a partial read access to him now.
            		 */
            		logger.info("Giving temporary read rights to confidential biobanker");
					setNonConfidential(true);
					setSelectedQuery(query);

					// also add it to the list of queries loaded, so it appears on the navigation in the left for
                    // convienience
                    OwnerQueryStatsDTO addme = new OwnerQueryStatsDTO();
                    addme.setQuery(query);
                    Person queryAuthor = DbUtil.getPersonDetails(config, query.getResearcherId());
                    addme.setQueryAuthor(queryAuthor);
					queries.add(0, addme);
					return null;
				}
            }


        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }

        return null;
	}

    /**
     * Leave query as a bio bank owner.
     *
     * @param queryDto
     * @return
     */
    public void ignoreQuery(OwnerQueryStatsDTO queryDto) {
        try (Config config = ConfigFactory.get()) {
			config.commit();
            queries = null;
            flagQuery(queryDto, Flag.IGNORED);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Mark query as starred
     * @param queryDto
     */
    public void starQuery(OwnerQueryStatsDTO queryDto){
        flagQuery(queryDto, Flag.STARRED);
    }

    /**
     * Mark query as archived
     * @param queryDto
     */
    public void archiveQuery(OwnerQueryStatsDTO queryDto){
        flagQuery(queryDto, Flag.ARCHIVED);
    }

    /**
     * Mark the given query with the given flag.
     * @param queryDto
     * @param flag
     */
    private void flagQuery(OwnerQueryStatsDTO queryDto, Flag flag) {
        try (Config config = ConfigFactory.get()) {
			DbUtil.flagQuery(config, queryDto, flag, userBean.getUserId());
            config.get().commit();
            queries = null;
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }



	/**
     * Sorts the queries such that the archived ones appear at the end.
     *
     * @return
     */
    public void sortQueries(){
        if (queries == null || queries.isEmpty()) {
            return;
        } else {
            Collections.sort(queries, new Comparator<OwnerQueryStatsDTO>() {
                @Override
                public int compare(OwnerQueryStatsDTO obj1, OwnerQueryStatsDTO obj2) {
                    if(obj1.isArchived() && obj2.isArchived()) {
                        return 0;
                    } else if(obj1.isArchived()) {
                        return 1;
                    } else if(obj2.isArchived()) {
                        return -1;
                    } else {
                        return 0;
                    }
                }
            });

        }
    }

	/**
	 * Add search filter
	 */
	public void addFilter() {
		queries = null;
		sessionBean.addFilter();
	}

	/**
	 * Removes the search filter.
	 *
	 * @param arg
	 *
	 */
	public void removeFilter(String arg) {
		queries = null;
		sessionBean.removeFilter(arg);
	}

	/**
	 * Split search terms by list of delimiters
	 * @return unique search terms
	 */
	public Set<String> getFilterTerms() {

src/main/webapp/owner/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
  ~ Deutsches Krebsforschungszentrum in Heidelberg
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see http://www.gnu.org/licenses.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:bbmricc="http://xmlns.jcp.org/jsf/composite/bbmri"
                template="../components/default.xhtml">

    <!-- Queries page for the owner -->
    
    
    <f:metadata>
		<f:viewParam name="flag" value="#{ownerQueriesBean.flagFilter}" />
		<f:viewAction action="#{sessionBean.clearAllFilters()}" />
	</f:metadata>
		
        

    <ui:param name="bodyClass" value="container body-nomargin"/>
	
    <ui:define name="body">
        <h:panelGroup layout="block" styleClass="row">
            <h3>#{label[ownerQueriesBean.pagetitle]}</h3>
        </h:panelGroup>
		<h:panelGroup
			rendered="#{ownerQueriesBean.queries.size() > 0 or ownerQueriesBean.filterTerms.size() > 0}"
			layout="block">
			<bbmricc:search backingBean="#{ownerQueriesBean}" />
		</h:panelGroup>

		<h:panelGroup
			rendered="#{ownerQueriesBean.queries.size() == 0 and ownerQueriesBean.filterTerms.size() > 0}"
			layout="block" styleClass="col-md-12">
			<h3>#{label['queryview.noSearchResults']}</h3>
		</h:panelGroup>

		<h:panelGroup layout="block">
            <h:panelGroup rendered="#{ownerQueriesBean.queries.size() == 0 and ownerQueriesBean.filterTerms.size() == 0}" layout="block">
                <h3>#{label['queryview.noQueries']}</h3>
            </h:panelGroup>

            <ui:repeat var="queryDto" value="#{ownerQueriesBean.getQueries()}">

                <h:panelGroup layout="block" styleClass="deco-none">
                    <h:panelGroup layout="block" styleClass="panel panel-default clickable #{queryDto.isArchived() ? 'archived-query' : ''} ">
                        <h:panelGroup layout="block" styleClass="panel-heading">
                            <h:form id="queryItemActions">
                                <h:commandLink styleClass="#{queryDto.isStarred() ? 'btn btn-primary' : 'btn btn-default'} btn-xs"
                                               title="#{queryDto.isStarred() ? label['queryview.queryitem.action.unmarkFavorite'] : label['queryview.queryitem.action.markFavorite']}"
                                               action="#{ownerQueriesBean.starQuery(queryDto)}">
                                    <i class="fa fa-star"></i>
                                </h:commandLink>

                                <h:link outcome="detail" title="#{label['queryview.queryitem.action.clickme']}" style="margin-left: 30px;" styleClass="detailLink">
                                    <f:param name="queryId" value="#{queryDto.query.id}"/>
                                    <f:param name="flag" value="#{ownerQueriesBean.flagFilter}"/>
                                    <h:outputText value="#{queryDto.query.title}"/>
                                </h:link>

                                <h:panelGroup styleClass="pull-right">

                                    <h:panelGroup layout="block" styleClass="btn-group queryActionButtons pull-right" role="group" aria-label="...">

                                        <h:commandLink  styleClass="#{queryDto.isArchived() ? 'btn btn-primary' : 'btn btn-default'}"
                                        title="#{queryDto.isArchived() ? label['queryview.queryitem.action.unArchiveMe'] : label['queryview.queryitem.action.archiveMe']}"
                                                        action="#{ownerQueriesBean.archiveQuery(queryDto)}">
                                            <i class="fa fa-folder-open"></i>
                                        </h:commandLink>

                                        <h:commandLink styleClass="#{queryDto.isIgnored() ? 'btn btn-primary' : 'btn btn-default'}"

                                        title="#{queryDto.isIgnored() ? label['queryview.queryitem.action.unIgnoreMe'] : label['queryview.queryitem.action.ignoreMe']}"
                                                       action="#{ownerQueriesBean.ignoreQuery(queryDto)}">
                                            <i class="fa fa-sign-out"></i>
                                        </h:commandLink>

                                    </h:panelGroup>

                                    <h:panelGroup styleClass="badge queryNumberResponsesBadge" rendered="#{queryDto.commentCount > 0}">
                                        <h:outputText title="#{queryDto.commentCount} #{label['queryview.queryitem.amount.comments.text']}"
                                                      value="#{queryDto.commentCount}"/>
                                    </h:panelGroup>

                                </h:panelGroup>
                            </h:form>
                        </h:panelGroup>

                        <h:panelGroup layout="block" styleClass="panel-body">
                            <h:panelGroup layout="block" styleClass="row">
                                <h:panelGroup layout="block" styleClass="col-xs-2 col-md-1">
                                    <bbmricc:avatar person="#{queryDto.queryAuthor}"/>
                                </h:panelGroup>

                                <h:panelGroup layout="block" styleClass="col-xs-10 col-md-11">
                                    <h:panelGroup layout="block" styleClass="row queryOwner">
                                        #{queryDto.queryAuthor.authName}
                                    </h:panelGroup>

                                    <h:panelGroup layout="block" styleClass="row">
                                        <h:panelGroup layout="block" styleClass="col-md-12 truncate-panel">
                                            #{queryDto.query.text}
                                        </h:panelGroup>
                                    </h:panelGroup>

                                    <h:panelGroup layout="block" styleClass="row">
                                        <h:panelGroup layout="block" styleClass="col-md-12">
                                            <h:panelGroup styleClass="pull-right">

                                                <h:outputText
                                                    value="#{queryDto.query.queryCreationTime}"
                                                    title="#{label['queryview.queryitem.datetime.creation']}">
                                                    <f:convertDateTime pattern="dd/MM/yyyy hh:mm" />
                                                </h:outputText>
                                            </h:panelGroup>
                                        </h:panelGroup>
                                    </h:panelGroup>
                                </h:panelGroup>

                            </h:panelGroup>
                        </h:panelGroup>
                    </h:panelGroup>
                </h:panelGroup>

            </ui:repeat>

            <h:outputScript>
                $(function() {
                    setupQueryLinks();
                });
            </h:outputScript>
        </h:panelGroup>
    </ui:define>

</ui:composition>