src/main/java/de/samply/bbmri/negotiator/model/OwnerQueryStatsDTO.java
/**
 * Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
 * Deutsches Krebsforschungszentrum in Heidelberg
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.bbmri.negotiator.model;

import de.samply.bbmri.negotiator.jooq.enums.Flag;

/**
 * DTO that gives a small statistic for a query, with the amount of commentCount
 * made for the query and the last time someone made a comment for this query,
 * and the name of the query creator
 */
public class OwnerQueryStatsDTO extends QueryStatsDTO {
	private static final long serialVersionUID = 1L;

	private Flag flag;

    public boolean isStarred() {
        return flag == Flag.STARRED;
    }

    public boolean isArchived() {
        return flag == Flag.ARCHIVED;
    }

    public boolean isIgnored() {
        return flag == Flag.IGNORED;
    }

	public Flag getFlag() {
		return flag;
	}

	public void setFlag(Flag flag) {
		this.flag = flag;
	}
}

src/main/java/de/samply/bbmri/negotiator/control/UserBean.java
/**
 * Copyright (C) 2016 Medizinische Informatik in der Translationalen Onkologie,
 * Deutsches Krebsforschungszentrum in Heidelberg
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.bbmri.negotiator.control;

import java.io.IOException;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import com.docuverse.identicon.IdenticonUtil;

import com.nimbusds.jwt.JWTClaimsSet;
import de.samply.bbmri.auth.client.AuthClient;
import de.samply.bbmri.auth.client.InvalidKeyException;
import de.samply.bbmri.auth.client.InvalidTokenException;
import de.samply.bbmri.auth.client.jwt.JWTAccessToken;
import de.samply.bbmri.auth.client.jwt.JWTIDToken;
import de.samply.bbmri.auth.client.jwt.JWTRefreshToken;
import de.samply.bbmri.auth.rest.Scope;
import de.samply.bbmri.auth.utils.OAuth2ClientConfig;
import de.samply.bbmri.negotiator.Config;
import de.samply.bbmri.negotiator.ConfigFactory;
import de.samply.bbmri.negotiator.NegotiatorConfig;
import de.samply.bbmri.negotiator.db.util.DbUtil;
import de.samply.bbmri.negotiator.jooq.Tables;
import de.samply.bbmri.negotiator.jooq.tables.pojos.Biobank;
import de.samply.bbmri.negotiator.jooq.tables.pojos.Collection;
import de.samply.bbmri.negotiator.jooq.tables.pojos.Person;
import de.samply.bbmri.negotiator.jooq.tables.records.PersonRecord;
import de.samply.common.config.OAuth2Client;
import de.samply.string.util.StringUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Sessionscoped bean for all data of the session about the user.
 */
@ManagedBean
@SessionScoped
public class UserBean implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Logger logger = LoggerFactory.getLogger(UserBean.class);

	/**
	 * The subjects from the dummy data.
	 */
	public static final String DUMMY_DATA_SUBJECT_RESEARCHER = "https://auth-dev.mitro.dkfz.de/users/8";
	public static final String DUMMY_DATA_SUBJECT_BIOBANK_OWNER = "https://auth-dev.mitro.dkfz.de/users/7";

	/**
	 * The current userEmail (email). Null if the login is not valid
	 */
	private String userEmail = null;

	/**
	 * The current real name. Null if the login is not valid.
	 */
	private String userRealName = null;

	/**
	 * The current user identity (usually a URL that identifies the user). Null if the login is not valid.
	 */
	private String userIdentity = null;

	/**
	 * If the login is valid this value is true. False otherwise.
	 */
	private Boolean loginValid = false;

	/**
	 * If the user is a biobank owner or not.
	 */
	private Boolean biobankOwner = false;

	/**
	 * If the user is a researcher or not.
	 */
	private Boolean researcher = false;

	/**
	 * ID of the Location (only biobank owners)
	 */
	private Biobank biobank = null;

	/**
	 * The *mapped* user ID in the database.
	 */
	private int userId = 0;

	/** The JWTs from OAuth2. */
	private JWTAccessToken accessToken;

	/** The JWT Open ID token. */
	private JWTIDToken idToken;

	/** The JWT refresh token. */
	private JWTRefreshToken refreshToken;

	/**
	 * The state of this session. This is a random string for OAuth2 used to prevent cross site forgery attacks.
	 */
	private String state;

	/**
	 * The Person from the database.
	 */
	private Person person;

    /**
     * The redirect URL used when the user lands at the negotiator from the directory, after making a new query. It contains the temporary query id.
     */
    private String newQueryRedirectURL;

	/**
	 * The collections of this user
	 */
	private List<Collection> collections;

    /**
     * The identity string of the user who sudo'd another
     */
    private String sudoMaster = null;

    private Boolean isAdmin = false;

	/**
	 * Basic Constructor for when the user bean is created without dependency injection.
	 */
	public UserBean() {
		init();
	}

    public String getSudoMaster() {
        return sudoMaster;
    }

    public void setSudoMaster(String sudoMaster) {
        this.sudoMaster = sudoMaster;
    }

    public Boolean sudoedUser() {
	    return sudoMaster!=null;
    }

    /**
	 * Executes a logout.
	 *
	 * @throws IOException
	 *             Signals that an I/O exception has occurred.
	 */
	public void logout() throws IOException {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();

	    // a sudoed user logs out back to his original self
	    if(sudoedUser()) {
	        unsudoUser();
	        context.redirect("/admin/index.xhtml");
	        return;
        }

		OAuth2Client config = NegotiatorConfig.get().getOauth2();

		// invalidate session all session scoped beans are destroyed and a new
		// login won't steal old values
		context.invalidateSession();

        if(NegotiatorConfig.get().getNegotiator().isAuthenticationDisabled()) {
            /**
             * If authentication is disabled, redirect the user back to the root folder of this application
             */
            context.redirect(context.getRequestContextPath());
        } else {
            context.redirect(context.getRequestContextPath() + "/logout.xhtml");
        }
	}

	/**
	 * Inits the state.
	 */
	@PostConstruct
	public void init() {
		// create the session state
		state = new BigInteger(64, new SecureRandom()).toString(32);
	}

	/**
	 * Returns the URL for Perun
	 *
	 * @return the authentication url
	 * @throws UnsupportedEncodingException
	 *             the unsupported encoding exception
	 */
	public String getAuthenticationUrl() throws UnsupportedEncodingException {
		ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest req = (HttpServletRequest) context.getRequest();
		return getAuthenticationUrl(req);
	}

    /**
     * Returns an auth URL that provides /index.xhtml as redirect url always
     * @param request
     * @return
     * @throws UnsupportedEncodingException
     */
    public String getAuthenticationUrlIndex(HttpServletRequest request) throws UnsupportedEncodingException {

        // TODO: Add path, in case negotiator is not deployed in ROOT
        String requestURL = "/index.xhtml";

        return OAuth2ClientConfig.getRedirectUrl(NegotiatorConfig.get().getOauth2(), request.getScheme(),
                request.getServerName(), request.getServerPort(), request.getContextPath(),
                requestURL, state, Scope.OPENID, Scope.EMAIL, Scope.PROFILE, Scope.PHONE, Scope.GROUPNAMES);
    }


    /**
	 * Returns the URL for Perun
	 *
	 * @return the authentication url
	 * @throws UnsupportedEncodingException
	 *             the unsupported encoding exception
	 */
	public String getAuthenticationRegisterUrl() throws UnsupportedEncodingException {
		ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest req = (HttpServletRequest) context.getRequest();
		return getAuthenticationRegisterUrl(req);
	}

	/**
	 * Returns the URL to Perun for the given HttpServletRequest. Uses the request query string to determine the
	 * redirect URL back to the negotiator.
	 * @param request
	 * @return
	 * @throws UnsupportedEncodingException
     */
	public String getAuthenticationUrl(HttpServletRequest request) throws UnsupportedEncodingException {
		StringBuilder requestURL = new StringBuilder(request.getServletPath());


		/**
		 * Construct a redirect URL to the authentication system and back.
		 */

		if (request.getQueryString() != null) {
			requestURL.setLength(0);
			requestURL.append("/index.xhtml");
		    setNewQueryRedirectURL(request.getServletPath() + "?" + request.getQueryString());
		}

		return OAuth2ClientConfig.getRedirectUrl(NegotiatorConfig.get().getOauth2(), request.getScheme(),
				request.getServerName(), request.getServerPort(), request.getContextPath(),
				requestURL.toString(), state, Scope.OPENID, Scope.EMAIL, Scope.PROFILE, Scope.PHONE, Scope.GROUPNAMES);
	}

    /**
     * Returns the URL to Perun for the given HttpServletRequest. Uses the request query string to determine the
     * redirect URL back to the negotiator.
     * @param request
     * @return
     * @throws UnsupportedEncodingException
     */
    public String getAuthenticationRegisterUrl(HttpServletRequest request) throws UnsupportedEncodingException {
        StringBuilder requestURL = new StringBuilder(request.getServletPath());

        // replace last entry to register
        requestURL.setLength(0);
        requestURL.append("/register.xhtml");

        /**
         * Construct a redirect URL to the authentication system and back.
         */

src/main/webapp/components/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
>

<h:head>
    <title><ui:insert name="title">BBMRI.negotiator</ui:insert></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    
    <ui:include src="styles.xhtml" />

    <ui:insert name="head" />
</h:head>

<h:body styleClass="#{bodyClass}">

    <ui:include src="navbar.xhtml" />

    <div class="navbar-shadow" />

    <ui:insert name="body" />

</h:body>
</html>

src/main/webapp/components/dialog.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

        <div class="modal fade" id="errorDialog" tabindex="-1" role="dialog" aria-labelledby="errorMessages">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="errorMessages">Validation errors</h4>
                    </div>
                    <div class="modal-body">
                        <span>#{msg.errors}</span>

                        <h:messages showSummary="true" showDetail="true" styleClass="list-group" errorClass="list-group-item list-group-item-danger"/>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>

            <h:outputScript>
            $(function() {
                if(#{facesContext.messageList.size()} > 0;) {
                $("#errorDialog").modal("show");
                }
                });
            </h:outputScript>
        </div>

</ui:composition>

src/main/webapp/components/navbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<h:panelGroup styleClass="container" layout="block" id="navbar">
			<h:panelGroup layout="block" styleClass="navbar-header">

				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<h:link outcome="/index" styleClass="navbar-brand">
					<span class="projectName">#{label['queryview.bbmri']}
                        <span class="bbmriModule">#{label['queryview.negotiator']}

                        </span>
                    </span>
				</h:link>
			</h:panelGroup>


			<h:form>
				<h:panelGroup layout="block" styleClass="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<c:if test="#{userBean.biobankOwner}">
						    <li class="dropdown"><a href="#" class="dropdown-toggle"
							    data-toggle="dropdown" role="button" aria-haspopup="true"
							    aria-expanded="false" title="#{label['queryview.action.menu']}">#{label['queryview.myBiobank']}<span class="caret"></span></a>
							    <ul class="dropdown-menu">
								    <li>
								        <h:link outcome="/owner/index" value="#{label['queryview.inbox']}" title="#{label['queryview.action.viewInbox']}">  																		 
					  				    </h:link>
								
								    </li>
								    <li>
								        <h:link outcome="/owner/index" value="#{label['queryview.starred']}" title="#{label['queryview.action.viewStarred']}" >
								            <f:param name="flag" value="STARRED"/>  																		 
					  				    </h:link>								
								    </li>								
								    <li>								
								        <h:link outcome="/owner/index" value="#{label['queryview.archived']}" title="#{label['queryview.action.viewArchived']}" >
								            <f:param name="flag" value="ARCHIVED"/>  																		 
					  				    </h:link>								
								    </li>
								    <li>								
								        <h:link outcome="/owner/index" value="#{label['queryview.ignored']}" title="#{label['queryview.action.viewIgnored']}" >
								            <f:param name="flag" value="IGNORED"/>  																		 
					  			        </h:link>
								    </li>
							    </ul>
						    </li>
						</c:if>
						<c:if test="#{userBean.researcher}">
								    <li>
								        <h:link value="#{label['queryview.myCreatedQueries']}" outcome="/researcher/index.xhtml"> 
								        </h:link>								
								    </li>															
						</c:if>
						<ui:fragment rendered="#{userBean.isAdmin()}">
							<li>
								<h:link outcome="/admin/index">
									<h:outputText value="#{label['admin.interface']}"/>
								</h:link>
							</li>
						</ui:fragment>
					</ul>


					<ul class="nav navbar-nav navbar-right navbar-user">
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">
								#{label['navbar.help']}
							</a>
							<ul id="help" class="dropdown-menu">
								<li>
									<h:link outcome="/help/owner-product-tour">
										#{label['navbar.owner.product-tour']}
									</h:link>
								</li>
								<li>
									<h:link outcome="/help/researcher-product-tour">
										#{label['navbar.researcher.product-tour']}
									</h:link>
								</li>
							</ul>
						</li>

						<ui:fragment rendered="#{! userBean.loginValid}">
							<li class="pull-right">
								<a href="#{userBean.authenticationUrl}">#{label['queryview.login']}</a>
							</li>
						</ui:fragment>

						<ui:fragment rendered="#{userBean.loginValid}">
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									<ui:fragment rendered="#{!userBean.sudoedUser()}">
                                        <i class="fa fa-user fa-fw userIcon" />
                                    </ui:fragment>
                                    <ui:fragment rendered="#{userBean.sudoedUser()}">
                                        <i class="fa fa-user-secret fa-fw userIcon" />
                                    </ui:fragment>
									#{userBean.userRealName.trim().length() > 0 ?
									userBean.userRealName : userBean.userEmail} <span class="caret"></span>
								</a>
								<ul id="userPanel" class="dropdown-menu">
									<li>
										<h:commandLink action="#{userBean.logout}">
											<i class="fa fa-sign-out" /> #{label['queryview.logout']}
										</h:commandLink>
									</li>
								</ul></li>
						</ui:fragment>
					</ul>
				</h:panelGroup>
			</h:form>
		</h:panelGroup>

	</nav>
</ui:composition>

src/main/webapp/components/styles.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:outputStylesheet library="webjars" name="bootstrap/3.3.7-1/css/bootstrap-jsf.css" />
    <h:outputStylesheet library="webjars" name="font-awesome/4.7.0/css/font-awesome-jsf.css" />
    <h:outputStylesheet library="webjars" name="font-awesome/4.7.0/css/font-awesome.min-jsf.css" />
    <h:outputStylesheet library="webjar" name="samply/css/base.css" />
    <h:outputStylesheet library="webjar" name="samply/css/fadein.css" />
    <h:outputStylesheet library="webjar" name="samply/css/buttons.css" />
    <h:outputStylesheet library="webjars" name="jquery-ui/1.12.1/jquery-ui.css" />

    <h:outputStylesheet library="webjars" name="select2/4.0.3/css/select2.css" />
    <h:outputStylesheet library="webjars" name="datatables/1.10.16/css/dataTables.bootstrap.min.css" />
    <h:outputStylesheet library="webjars" name="jstree/3.3.4/dist/themes/default/style.min.css" />



    <h:outputStylesheet library="webjar" name="samply/css/demo-ribbon.css" />

    <h:outputStylesheet name="css/bbmri.css" />
    <h:outputStylesheet name="css/buttons.css" />
    <h:outputStylesheet name="css/negotiator.css" />


    <h:outputScript library="webjars" name="jquery/3.3.1/jquery.min.js" />
    <h:outputScript library="webjars" name="jquery-ui/1.12.1/jquery-ui.min.js" />
    <h:outputScript library="webjars" name="bootstrap/3.3.7-1/js/bootstrap.js" />
    <h:outputScript library="webjars" name="select2/4.0.3/js/select2.min.js" />
    <h:outputScript library="webjars" name="datatables/1.10.16/js/jquery.dataTables.min.js" />
    <h:outputScript library="webjars" name="datatables/1.10.16/js/dataTables.bootstrap.min.js" />
    <h:outputScript library="webjars" name="jstree/3.3.4/dist/jstree.min.js" />


    <!-- Preload the JSF library, otherwise the negotiator.js will not work -->
    <h:outputScript name="jsf.js" library="javax.faces"/>
    <h:outputScript name="js/negotiator.js" />
    <h:outputScript name="js/jquery.truncate.min.js" />


    <!-- The google Analytics script is only used on the negotiator.bbmri-eric.eu server -->
    <h:outputScript rendered="#{facesContext.externalContext.requestServerName == 'negotiator.bbmri-eric.eu'}">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function()
                { (i[r].q=i[r].q||[]).push(arguments)}

                ,i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-41289707-5', 'auto');
        ga('send', 'pageview');
    </h:outputScript>

</ui:composition>